openapi: 3.1.0
info:
  title: brainstorm
  version: '1.0'
  summary: API for the Brainstorm app
  contact:
    name: Alex Petrean
    email: alex.petrean@stud.ubbcluj.ro
  description: Rest API
servers:
  - url: 'http://localhost:5000'
  - url: 'http://localhost:5001'
    description: ''
paths:
  /AppVersion/version:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionCode'
      operationId: get-AppVersion-version
      description: Retrieves the version of the app
components:
  schemas:
    VersionCode:
      title: VersionCode
      type: object
      examples:
        - version: '1.5'
      description: The version of the app.
      properties:
        version:
          type: string
          pattern: '[0-9]\.[0-9]'
          readOnly: true
      required:
        - version
